/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Muns.*;
import OlympicGames.*;
import OtherGames.*;
import Simulation.*;
import java.awt.Color;

/**
 *
 * @author Flia_Salinas
 */
public class FrameInicio extends javax.swing.JFrame {

    /**
     * Creates new form FrameInicio
     */
    public FrameInicio() {
        initComponents();
        getContentPane().setBackground(new Color(0, 51, 51));
        setTitle("Select Mode");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblMode = new javax.swing.JLabel();
        PanelOlympics = new javax.swing.JPanel();
        PanelClubs = new javax.swing.JPanel();
        BtnClubs = new javax.swing.JButton();
        BtnAutoClb = new javax.swing.JButton();
        BtnClubsTournaments = new javax.swing.JButton();
        PanelSports = new javax.swing.JPanel();
        BtnFootball = new javax.swing.JButton();
        BtnSportsTournaments = new javax.swing.JButton();
        BtnLeaguesS = new javax.swing.JButton();
        BtnOlSym = new javax.swing.JButton();
        PanelGames = new javax.swing.JPanel();
        BtnGames = new javax.swing.JButton();
        BtnGamesTournaments = new javax.swing.JButton();
        BtnLeaguesG = new javax.swing.JButton();
        PanelClubs1 = new javax.swing.JPanel();
        BtnMuns = new javax.swing.JButton();
        BtnMunsTournaments = new javax.swing.JButton();
        BtnCities = new javax.swing.JButton();
        BtnCitiesTournaments = new javax.swing.JButton();
        BtnCitiesLeagues = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblMode.setBackground(new java.awt.Color(0, 51, 51));
        LblMode.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        LblMode.setForeground(new java.awt.Color(255, 255, 255));
        LblMode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMode.setText("Football & Olympics");
        LblMode.setOpaque(true);

        PanelOlympics.setBackground(new java.awt.Color(0, 51, 51));
        PanelOlympics.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        PanelClubs.setBackground(new java.awt.Color(0, 51, 51));
        PanelClubs.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Clubs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel Light", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        BtnClubs.setBackground(new java.awt.Color(0, 102, 102));
        BtnClubs.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnClubs.setForeground(new java.awt.Color(255, 255, 255));
        BtnClubs.setText("Clubs Manual");
        BtnClubs.setBorder(null);
        BtnClubs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClubsActionPerformed(evt);
            }
        });

        BtnAutoClb.setBackground(new java.awt.Color(0, 102, 102));
        BtnAutoClb.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnAutoClb.setForeground(new java.awt.Color(255, 255, 255));
        BtnAutoClb.setText("Clubs Leagues");
        BtnAutoClb.setBorder(null);
        BtnAutoClb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAutoClbActionPerformed(evt);
            }
        });

        BtnClubsTournaments.setBackground(new java.awt.Color(0, 102, 102));
        BtnClubsTournaments.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnClubsTournaments.setForeground(new java.awt.Color(255, 255, 255));
        BtnClubsTournaments.setText("Clubs Tournaments");
        BtnClubsTournaments.setBorder(null);
        BtnClubsTournaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnClubsTournamentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelClubsLayout = new javax.swing.GroupLayout(PanelClubs);
        PanelClubs.setLayout(PanelClubsLayout);
        PanelClubsLayout.setHorizontalGroup(
            PanelClubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClubsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClubsLayout.createSequentialGroup()
                        .addComponent(BtnClubs, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAutoClb, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnClubsTournaments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelClubsLayout.setVerticalGroup(
            PanelClubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClubsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClubsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnClubs)
                    .addComponent(BtnAutoClb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnClubsTournaments)
                .addContainerGap())
        );

        PanelSports.setBackground(new java.awt.Color(0, 51, 51));
        PanelSports.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Sports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel Light", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        BtnFootball.setBackground(new java.awt.Color(0, 102, 102));
        BtnFootball.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnFootball.setForeground(new java.awt.Color(255, 255, 255));
        BtnFootball.setText("Sports Manual");
        BtnFootball.setBorder(null);
        BtnFootball.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFootballActionPerformed(evt);
            }
        });

        BtnSportsTournaments.setBackground(new java.awt.Color(0, 102, 102));
        BtnSportsTournaments.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnSportsTournaments.setForeground(new java.awt.Color(255, 255, 255));
        BtnSportsTournaments.setText("Sports Tournaments");
        BtnSportsTournaments.setBorder(null);
        BtnSportsTournaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSportsTournamentsActionPerformed(evt);
            }
        });

        BtnLeaguesS.setBackground(new java.awt.Color(0, 102, 102));
        BtnLeaguesS.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnLeaguesS.setForeground(new java.awt.Color(255, 255, 255));
        BtnLeaguesS.setText("Sports Leagues");
        BtnLeaguesS.setBorder(null);
        BtnLeaguesS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLeaguesSActionPerformed(evt);
            }
        });

        BtnOlSym.setBackground(new java.awt.Color(0, 102, 102));
        BtnOlSym.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnOlSym.setForeground(new java.awt.Color(255, 255, 255));
        BtnOlSym.setText("Sports Simulation");
        BtnOlSym.setBorder(null);
        BtnOlSym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOlSymActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSportsLayout = new javax.swing.GroupLayout(PanelSports);
        PanelSports.setLayout(PanelSportsLayout);
        PanelSportsLayout.setHorizontalGroup(
            PanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnLeaguesS, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addComponent(BtnFootball, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(PanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnOlSym, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnSportsTournaments, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelSportsLayout.setVerticalGroup(
            PanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFootball)
                    .addComponent(BtnSportsTournaments))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelSportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLeaguesS)
                    .addComponent(BtnOlSym))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelGames.setBackground(new java.awt.Color(0, 51, 51));
        PanelGames.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Games", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel Light", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        BtnGames.setBackground(new java.awt.Color(0, 102, 102));
        BtnGames.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnGames.setForeground(new java.awt.Color(255, 255, 255));
        BtnGames.setText("Games Manual");
        BtnGames.setBorder(null);
        BtnGames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGamesActionPerformed(evt);
            }
        });

        BtnGamesTournaments.setBackground(new java.awt.Color(0, 102, 102));
        BtnGamesTournaments.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnGamesTournaments.setForeground(new java.awt.Color(255, 255, 255));
        BtnGamesTournaments.setText("GamesTournaments");
        BtnGamesTournaments.setBorder(null);
        BtnGamesTournaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGamesTournamentsActionPerformed(evt);
            }
        });

        BtnLeaguesG.setBackground(new java.awt.Color(0, 102, 102));
        BtnLeaguesG.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnLeaguesG.setForeground(new java.awt.Color(255, 255, 255));
        BtnLeaguesG.setText("Games Leagues");
        BtnLeaguesG.setBorder(null);
        BtnLeaguesG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLeaguesGActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelGamesLayout = new javax.swing.GroupLayout(PanelGames);
        PanelGames.setLayout(PanelGamesLayout);
        PanelGamesLayout.setHorizontalGroup(
            PanelGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGamesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelGamesLayout.createSequentialGroup()
                        .addComponent(BtnGames, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(BtnLeaguesG, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnGamesTournaments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelGamesLayout.setVerticalGroup(
            PanelGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGamesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelGamesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGames)
                    .addComponent(BtnLeaguesG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnGamesTournaments)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelClubs1.setBackground(new java.awt.Color(0, 51, 51));
        PanelClubs1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Muns", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel Light", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        BtnMuns.setBackground(new java.awt.Color(0, 102, 102));
        BtnMuns.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnMuns.setForeground(new java.awt.Color(255, 255, 255));
        BtnMuns.setText("Muns Manual");
        BtnMuns.setBorder(null);
        BtnMuns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMunsActionPerformed(evt);
            }
        });

        BtnMunsTournaments.setBackground(new java.awt.Color(0, 102, 102));
        BtnMunsTournaments.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnMunsTournaments.setForeground(new java.awt.Color(255, 255, 255));
        BtnMunsTournaments.setText("Muns Tournaments");
        BtnMunsTournaments.setBorder(null);
        BtnMunsTournaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMunsTournamentsActionPerformed(evt);
            }
        });

        BtnCities.setBackground(new java.awt.Color(0, 102, 102));
        BtnCities.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnCities.setForeground(new java.awt.Color(255, 255, 255));
        BtnCities.setText("Cities Manual");
        BtnCities.setBorder(null);
        BtnCities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCitiesActionPerformed(evt);
            }
        });

        BtnCitiesTournaments.setBackground(new java.awt.Color(0, 102, 102));
        BtnCitiesTournaments.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnCitiesTournaments.setForeground(new java.awt.Color(255, 255, 255));
        BtnCitiesTournaments.setText("Cities Tournaments");
        BtnCitiesTournaments.setBorder(null);
        BtnCitiesTournaments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCitiesTournamentsActionPerformed(evt);
            }
        });

        BtnCitiesLeagues.setBackground(new java.awt.Color(0, 102, 102));
        BtnCitiesLeagues.setFont(new java.awt.Font("Corbel Light", 1, 16)); // NOI18N
        BtnCitiesLeagues.setForeground(new java.awt.Color(255, 255, 255));
        BtnCitiesLeagues.setText("Cities Leagues");
        BtnCitiesLeagues.setBorder(null);
        BtnCitiesLeagues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCitiesLeaguesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelClubs1Layout = new javax.swing.GroupLayout(PanelClubs1);
        PanelClubs1.setLayout(PanelClubs1Layout);
        PanelClubs1Layout.setHorizontalGroup(
            PanelClubs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClubs1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClubs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCitiesLeagues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelClubs1Layout.createSequentialGroup()
                        .addComponent(BtnCities, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCitiesTournaments, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelClubs1Layout.createSequentialGroup()
                        .addComponent(BtnMuns, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(BtnMunsTournaments, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelClubs1Layout.setVerticalGroup(
            PanelClubs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClubs1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClubs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnMuns)
                    .addComponent(BtnMunsTournaments))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelClubs1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnCities)
                    .addComponent(BtnCitiesTournaments))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCitiesLeagues)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelOlympicsLayout = new javax.swing.GroupLayout(PanelOlympics);
        PanelOlympics.setLayout(PanelOlympicsLayout);
        PanelOlympicsLayout.setHorizontalGroup(
            PanelOlympicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOlympicsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOlympicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelSports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelGames, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelClubs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelClubs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelOlympicsLayout.setVerticalGroup(
            PanelOlympicsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOlympicsLayout.createSequentialGroup()
                .addComponent(PanelSports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelClubs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelClubs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelOlympics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LblMode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblMode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelOlympics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFootballActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFootballActionPerformed
        FrameOlympic b = new FrameOlympic();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnFootballActionPerformed

    private void BtnLeaguesSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLeaguesSActionPerformed
        ManyMatchesSports m = new ManyMatchesSports();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLeaguesSActionPerformed

    private void BtnOlSymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOlSymActionPerformed
        OlympicSimulation m = new OlympicSimulation();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnOlSymActionPerformed

    private void BtnClubsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClubsActionPerformed
        FrameClubs b = new FrameClubs();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnClubsActionPerformed

    private void BtnAutoClbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAutoClbActionPerformed
        ManyMatchesClubs m = new ManyMatchesClubs();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnAutoClbActionPerformed

    private void BtnSportsTournamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSportsTournamentsActionPerformed
        FrameEliminationSports b = new FrameEliminationSports();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnSportsTournamentsActionPerformed

    private void BtnGamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGamesActionPerformed
        FrameGames b = new FrameGames();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnGamesActionPerformed

    private void BtnLeaguesGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLeaguesGActionPerformed
        ManyMatchesGames m = new ManyMatchesGames();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnLeaguesGActionPerformed

    private void BtnGamesTournamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGamesTournamentsActionPerformed
        FrameEliminationGames b = new FrameEliminationGames();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnGamesTournamentsActionPerformed

    private void BtnClubsTournamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnClubsTournamentsActionPerformed
        FrameEliminationClubs b = new FrameEliminationClubs();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnClubsTournamentsActionPerformed

    private void BtnMunsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMunsActionPerformed
        FrameMuns b = new FrameMuns();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnMunsActionPerformed

    private void BtnMunsTournamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMunsTournamentsActionPerformed
        FrameEliminationMuns b = new FrameEliminationMuns();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnMunsTournamentsActionPerformed

    private void BtnCitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCitiesActionPerformed
        FrameCities b = new FrameCities();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCitiesActionPerformed

    private void BtnCitiesTournamentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCitiesTournamentsActionPerformed
        FrameEliminationCities b = new FrameEliminationCities();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCitiesTournamentsActionPerformed

    private void BtnCitiesLeaguesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCitiesLeaguesActionPerformed
        ManyMatchesCities b = new ManyMatchesCities();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnCitiesLeaguesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAutoClb;
    private javax.swing.JButton BtnCities;
    private javax.swing.JButton BtnCitiesLeagues;
    private javax.swing.JButton BtnCitiesTournaments;
    private javax.swing.JButton BtnClubs;
    private javax.swing.JButton BtnClubsTournaments;
    private javax.swing.JButton BtnFootball;
    private javax.swing.JButton BtnGames;
    private javax.swing.JButton BtnGamesTournaments;
    private javax.swing.JButton BtnLeaguesG;
    private javax.swing.JButton BtnLeaguesS;
    private javax.swing.JButton BtnMuns;
    private javax.swing.JButton BtnMunsTournaments;
    private javax.swing.JButton BtnOlSym;
    private javax.swing.JButton BtnSportsTournaments;
    private javax.swing.JLabel LblMode;
    private javax.swing.JPanel PanelClubs;
    private javax.swing.JPanel PanelClubs1;
    private javax.swing.JPanel PanelGames;
    private javax.swing.JPanel PanelOlympics;
    private javax.swing.JPanel PanelSports;
    // End of variables declaration//GEN-END:variables
}
