/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exports;

import Main.FrameInicio;
import Simulation.OlympicSimulation;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author Salinas
 */
public class OlympicSimulatorExport extends javax.swing.JFrame {

    /**
     * Creates new form OlympicSimulatorExport
     */
    private OlympicSimulation sim_frame;
    private ArrayList<String> current_categories = new ArrayList<>();
    private ArrayList<String> current_sports = new ArrayList<>();
    private JComboBox current_game_box;
    private JComboBox current_category_box;
    private JComboBox current_sport_box;
    private ArrayList<ArrayList<Object>> table_models = new ArrayList<>();

    public OlympicSimulatorExport() {
        initComponents();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(0, 51, 51));
        setResizable(false);
        setTitle("Exportador Juegos Olímpicos");
        this.sim_frame = new OlympicSimulation();
        this.BtnGenerate.setEnabled(false);
    }

    public void getCategories() {
        this.current_categories.clear();
        ComboBoxModel model = this.current_category_box.getModel();
        for (int i = 0; i < model.getSize(); i++) {
            this.current_categories.add((String) this.current_category_box.getItemAt(i));
        }
    }

    public void getSports() {
        this.current_sports.clear();
        ComboBoxModel model = this.current_sport_box.getModel();
        for (int i = 0; i < model.getSize(); i++) {
            this.current_sports.add((String) this.current_sport_box.getItemAt(i));
        }
    }

    public void exportToExcel(ArrayList<ArrayList<Object>> tables, String filePath) throws FileNotFoundException, IOException {
        System.out.println(filePath);
        Workbook workbook = new HSSFWorkbook();
        Row row;
        Cell cell;

        ArrayList<DefaultTableModel> table = new ArrayList<>();
        ArrayList<String> sports_names = new ArrayList<>();

        for (ArrayList<Object> obj : tables) {
            table.add((DefaultTableModel) obj.get(0));
            sports_names.add((String) obj.get(1));
        }

        int index = 0;

        for (DefaultTableModel mdl : table) {
            DefaultTableModel model = mdl;
            Sheet sheet = workbook.createSheet(sports_names.get(index));
            // write the column headers
            row = sheet.createRow(0);
            for (int c = 0; c < model.getColumnCount(); c++) {
                cell = row.createCell(c);
                cell.setCellValue(model.getColumnName(c));
            }

            // write the data rows
            for (int r = 0; r < model.getRowCount(); r++) {
                row = sheet.createRow(r + 1);
                for (int c = 0; c < model.getColumnCount(); c++) {
                    cell = row.createCell(c);
                    Object value = model.getValueAt(r, c);
                    if (value instanceof String) {
                        cell.setCellValue((String) value);
                    } else if (value instanceof Double) {
                        cell.setCellValue((Double) value);
                    }else if (value instanceof Integer) {
                        cell.setCellValue((Integer) value);
                    }
                }
            }
            index++;
        }

        FileOutputStream out = new FileOutputStream(filePath);
        workbook.write(out);
        out.close();
        workbook.close();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelData = new javax.swing.JPanel();
        LblGame = new javax.swing.JLabel();
        BoxGame = new javax.swing.JComboBox<>();
        BtnGenerate = new javax.swing.JButton();
        BtnBack = new javax.swing.JButton();
        BtnCheckAll = new javax.swing.JCheckBox();
        LblPeriod = new javax.swing.JLabel();
        BoxPeriods = new javax.swing.JComboBox<>();
        LblFrom = new javax.swing.JLabel();
        LblTo = new javax.swing.JLabel();
        BoxFrom = new javax.swing.JComboBox<>();
        BoxTo = new javax.swing.JComboBox<>();
        PanelData1 = new javax.swing.JPanel();
        LblFileName = new javax.swing.JLabel();
        TxtFileName = new javax.swing.JTextField();
        LblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelData.setBackground(new java.awt.Color(0, 51, 51));
        PanelData.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel Light", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PanelData.setForeground(new java.awt.Color(0, 51, 51));

        LblGame.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        LblGame.setForeground(new java.awt.Color(255, 255, 255));
        LblGame.setText("Juego");

        BoxGame.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        BoxGame.setForeground(new java.awt.Color(255, 255, 255));
        BoxGame.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Game>", "Londres", "Invierno", "Tokyo", "Excitebike", "Formula 1", "F-Zero", "Goldeneye", "Mario Kart", "SSB", "Muñecos" }));
        BoxGame.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BoxGameItemStateChanged(evt);
            }
        });
        BoxGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxGameActionPerformed(evt);
            }
        });

        BtnGenerate.setBackground(new java.awt.Color(0, 102, 102));
        BtnGenerate.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        BtnGenerate.setForeground(new java.awt.Color(255, 255, 255));
        BtnGenerate.setText("Generar");
        BtnGenerate.setBorder(null);
        BtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGenerateActionPerformed(evt);
            }
        });

        BtnBack.setBackground(new java.awt.Color(0, 102, 102));
        BtnBack.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        BtnBack.setForeground(new java.awt.Color(255, 255, 255));
        BtnBack.setText("Back");
        BtnBack.setBorder(null);
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });

        BtnCheckAll.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        BtnCheckAll.setForeground(new java.awt.Color(255, 255, 255));
        BtnCheckAll.setText("Include All");

        LblPeriod.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        LblPeriod.setForeground(new java.awt.Color(255, 255, 255));
        LblPeriod.setText("Periodo");

        BoxPeriods.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        BoxPeriods.setForeground(new java.awt.Color(255, 255, 255));
        BoxPeriods.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Select Period Time>", "1", "2", "4" }));
        BoxPeriods.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BoxPeriodsItemStateChanged(evt);
            }
        });
        BoxPeriods.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxPeriodsActionPerformed(evt);
            }
        });

        LblFrom.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        LblFrom.setForeground(new java.awt.Color(255, 255, 255));
        LblFrom.setText("Desde");

        LblTo.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        LblTo.setForeground(new java.awt.Color(255, 255, 255));
        LblTo.setText("Hasta");

        BoxFrom.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        BoxFrom.setForeground(new java.awt.Color(255, 255, 255));
        BoxFrom.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BoxFromItemStateChanged(evt);
            }
        });
        BoxFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxFromActionPerformed(evt);
            }
        });

        BoxTo.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        BoxTo.setForeground(new java.awt.Color(255, 255, 255));
        BoxTo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BoxToItemStateChanged(evt);
            }
        });
        BoxTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxToActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDataLayout = new javax.swing.GroupLayout(PanelData);
        PanelData.setLayout(PanelDataLayout);
        PanelDataLayout.setHorizontalGroup(
            PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BoxGame, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                    .addComponent(LblGame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblPeriod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BoxPeriods, 0, 206, Short.MAX_VALUE)
                    .addGroup(PanelDataLayout.createSequentialGroup()
                        .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BoxFrom, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LblFrom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LblTo, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(BoxTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnCheckAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnGenerate, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelDataLayout.setVerticalGroup(
            PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDataLayout.createSequentialGroup()
                        .addComponent(BtnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCheckAll))
                    .addGroup(PanelDataLayout.createSequentialGroup()
                        .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblGame)
                            .addComponent(LblPeriod))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoxGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxPeriods, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblFrom)
                            .addComponent(LblTo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BoxFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        PanelData1.setBackground(new java.awt.Color(0, 51, 51));
        PanelData1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Corbel Light", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PanelData1.setForeground(new java.awt.Color(0, 51, 51));

        LblFileName.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        LblFileName.setForeground(new java.awt.Color(255, 255, 255));
        LblFileName.setText("Nombre del Archivo");

        LblStatus.setFont(new java.awt.Font("Corbel Light", 1, 12)); // NOI18N
        LblStatus.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelData1Layout = new javax.swing.GroupLayout(PanelData1);
        PanelData1.setLayout(PanelData1Layout);
        PanelData1Layout.setHorizontalGroup(
            PanelData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelData1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblFileName, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(TxtFileName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelData1Layout.setVerticalGroup(
            PanelData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelData1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelData1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelData1Layout.createSequentialGroup()
                        .addComponent(LblFileName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelData1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoxGameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BoxGameItemStateChanged

    }//GEN-LAST:event_BoxGameItemStateChanged

    private void BoxGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxGameActionPerformed

    }//GEN-LAST:event_BoxGameActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        FrameInicio f = new FrameInicio();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed

    private void BtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGenerateActionPerformed
        int from_year = Integer.parseInt((String) this.BoxFrom.getSelectedItem());
        int to_year = Integer.parseInt((String) this.BoxTo.getSelectedItem());
        int period = Integer.parseInt((String) this.BoxPeriods.getSelectedItem());

        if (this.BtnCheckAll.isSelected()) {
            this.sim_frame.setBoxAll(true);
            this.sim_frame.updateTeams();
        } else {
            this.sim_frame.setBoxAll(false);
            this.sim_frame.updateTeams();
        }

        for (int p = from_year; p <= to_year; p += period) {
            this.table_models.clear();
            String game = (String) this.BoxGame.getSelectedItem();
            System.out.println(game);
            this.sim_frame.setGame(game);
            this.current_game_box = this.sim_frame.getGameBox();
            this.current_category_box = this.sim_frame.getCategoryBox();
            this.getCategories();
            System.out.println(this.current_categories);

            for (String cat : this.current_categories) {
                this.sim_frame.setCategory(cat);
                this.current_sport_box = this.sim_frame.getSportBox();
                this.getSports();
                for (String sport : this.current_sports) {
                    this.sim_frame.setSport(sport);
                    this.sim_frame.simulateSport();
                    ArrayList<Object> objs = new ArrayList<>();
                    objs.add(this.sim_frame.getSimTable());
                    objs.add(sport);
                    this.table_models.add(objs);
                    System.out.println(this.current_sport_box.getSelectedItem() + ": ");
                    System.out.println(this.sim_frame.getSimTable());

                }
            }

            String fileName = this.TxtFileName.getText();
            if (fileName.isEmpty()) {
                fileName = "dumptest";
            }
            String filePath = "export/" + fileName + p + ".xls";

            try {
                this.exportToExcel(this.table_models, filePath);
                this.LblStatus.setText("El archivo " + fileName + p + " ha sido generado...");
            } catch (IOException ex) {
                this.LblStatus.setText("El archivo no ha sido generado...");
            }
        }


    }//GEN-LAST:event_BtnGenerateActionPerformed

    private void BoxPeriodsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BoxPeriodsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxPeriodsItemStateChanged

    private void BoxPeriodsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxPeriodsActionPerformed
        int value = Integer.parseInt((String) this.BoxPeriods.getSelectedItem());
        this.BoxFrom.removeAllItems();
        switch (value) {
            case 1:
                for (int i = 1880; i < 2200; i++) {
                    this.BoxFrom.addItem(i + "");
                }
                break;
            case 2:
                for (int i = 1880; i < 2200; i += 2) {
                    this.BoxFrom.addItem(i + "");
                }
                break;
            case 4:
                for (int i = 1880; i < 2200; i += 4) {
                    this.BoxFrom.addItem(i + "");
                }
                break;
            default:
                for (int i = 1880; i < 2200; i++) {
                    this.BoxFrom.addItem(i + "");
                }
                break;
        }
    }//GEN-LAST:event_BoxPeriodsActionPerformed

    private void BoxFromItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BoxFromItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxFromItemStateChanged

    private void BoxFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxFromActionPerformed
        int value = Integer.parseInt((String) this.BoxPeriods.getSelectedItem());
        int curr_time = Integer.parseInt((String) this.BoxFrom.getSelectedItem());
        this.BtnGenerate.setEnabled(true);
        this.BoxTo.removeAllItems();
        switch (value) {
            case 1:
                for (int i = curr_time; i < 2200; i++) {
                    this.BoxTo.addItem(i + "");
                }
                break;
            case 2:
                for (int i = curr_time; i < 2200; i += 2) {
                    this.BoxTo.addItem(i + "");
                }
                break;
            case 4:
                for (int i = curr_time; i < 2200; i += 4) {
                    this.BoxTo.addItem(i + "");
                }
                break;
            default:
                for (int i = curr_time; i < 2200; i++) {
                    this.BoxTo.addItem(i + "");
                }
                break;
        }
    }//GEN-LAST:event_BoxFromActionPerformed

    private void BoxToItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BoxToItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxToItemStateChanged

    private void BoxToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OlympicSimulatorExport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OlympicSimulatorExport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OlympicSimulatorExport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OlympicSimulatorExport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OlympicSimulatorExport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxFrom;
    private javax.swing.JComboBox<String> BoxGame;
    private javax.swing.JComboBox<String> BoxPeriods;
    private javax.swing.JComboBox<String> BoxTo;
    private javax.swing.JButton BtnBack;
    private javax.swing.JCheckBox BtnCheckAll;
    private javax.swing.JButton BtnGenerate;
    private javax.swing.JLabel LblFileName;
    private javax.swing.JLabel LblFrom;
    private javax.swing.JLabel LblGame;
    private javax.swing.JLabel LblPeriod;
    private javax.swing.JLabel LblStatus;
    private javax.swing.JLabel LblTo;
    private javax.swing.JPanel PanelData;
    private javax.swing.JPanel PanelData1;
    private javax.swing.JTextField TxtFileName;
    // End of variables declaration//GEN-END:variables
}
